import * as path from "path";
import * as fs from "fs";
import { spawn } from "child_process";
import {
  createConnection,
  TextDocuments,
  ProposedFeatures,
  InitializeParams,
  CompletionItem,
  CompletionItemKind,
  TextDocumentSyncKind,
  Hover,
  MarkupKind,
  SignatureHelp,
  SignatureInformation,
  ParameterInformation,
  DocumentSymbol,
  SymbolKind,
  Location,
  Range,
  Diagnostic,
  DiagnosticSeverity,
  CodeLens,
  CodeLensParams,
  FoldingRange,
  FoldingRangeKind,
  CodeAction,
  CodeActionKind,
  TextEdit,
  DocumentHighlightKind,
  SemanticTokensLegend,
  Position,
  SemanticTokensBuilder,
} from "vscode-languageserver/node";

import { TextDocument } from "vscode-languageserver-textdocument";
import { URI } from "vscode-uri";
import {
  buildModel as buildRegexModel,
  findWordAt,
  classContainingLine,
  KW,
  type KvalModel,
} from "./model";
import { resolveSymbolAt } from "./symbolResolve";
import {
  buildSymbolIndex,
  rangesOfWordPerLine,
  symbolOccurrenceRanges,
  type RefKind,
  type SymKind,
} from "./workspaceIndex";
import {
  buildSemanticTokens,
  SEMANTIC_TOKEN_MODIFIERS,
  SEMANTIC_TOKEN_TYPES,
} from "./semanticTokens";
import { formatKvalDocument, formatRange, type FormatOptions } from "./formatting";

const connection = createConnection(ProposedFeatures.all);
const documents = new TextDocuments(TextDocument);

let extensionRoot = "";
let pythonPath = "python";
let pythonSysPathRoot = "";
let diagnosticsEnabled = true;
let diagnosticsDelayMs = 400;
let workspaceRoots: string[] = [];

const docModels = new Map<string, KvalModel>();
const debouncers = new Map<string, ReturnType<typeof setTimeout>>();
const symDebouncers = new Map<string, ReturnType<typeof setTimeout>>();

const semanticLegend: SemanticTokensLegend = {
  tokenTypes: [...SEMANTIC_TOKEN_TYPES],
  tokenModifiers: [...SEMANTIC_TOKEN_MODIFIERS],
};

type BuiltinFunc = {
  name: string;
  signature: string;
  doc: string;
  returnType: string;
  params: string[];
};

let BUILTIN_FUNCS: BuiltinFunc[] = [
  { name: "print", signature: "void print(...args)", doc: "输出参数到标准输出。" },
  { name: "input", signature: 'string input(string prompt = "")', doc: "读取一行输入文本。" },
  { name: "ord", signature: "int ord(string s)", doc: "返回字符的整数编码（取首字符）。" },
  { name: "chr", signature: "string chr(int code)", doc: "将整数编码转换为单字符字符串。" },
].map((b) => ({
  ...b,
  returnType: b.signature.split(/\s+/)[0] ?? "object",
  params: splitParams((b.signature.match(/\((.*)\)/)?.[1] ?? "").trim()),
}));
let builtinDeclUri: string | null = null;
const builtinDeclLine = new Map<string, number>();
let builtinLoadInFlight = false;
const PREPROCESSOR_ITEMS: ReadonlyArray<{ label: string; insertText: string; doc: string }> = [
  {
    label: "#include",
    insertText: '#include "$1"',
    doc: '`#include <xxx>` 仅在 `Kval/Lib` 查找；`#include "xxx"` 先当前目录，再 `Kval/Lib`。',
  },
  { label: "#define", insertText: "#define ${1:NAME} ${2:VALUE}", doc: "定义对象式宏。" },
  { label: "#undef", insertText: "#undef ${1:NAME}", doc: "取消宏定义。" },
  { label: "#pragma once", insertText: "#pragma once", doc: "当前文件仅展开一次。" },
];

function builtinByName(name: string) {
  const normalized = name.startsWith("builtins::") ? name.slice("builtins::".length) : name;
  return BUILTIN_FUNCS.find((b) => b.name === normalized);
}

function preprocessByName(name: string) {
  const normalized = name.startsWith("#") ? name : `#${name}`;
  return PREPROCESSOR_ITEMS.find((p) => p.label === normalized);
}

function workspaceRootForGeneratedDecl(): string {
  if (workspaceRoots.length > 0) return workspaceRoots[0];
  if (pythonSysPathRoot) return pythonSysPathRoot;
  return process.cwd();
}

function generateBuiltinDeclFile(builtins: BuiltinFunc[]): void {
  const root = workspaceRootForGeneratedDecl();
  const dir = path.join(root, ".kval");
  const f = path.join(dir, "builtins.kvi");
  fs.mkdirSync(dir, { recursive: true });
  const lines: string[] = [];
  lines.push("// Auto-generated by Kval language server");
  lines.push("namespace builtins {");
  builtinDeclLine.clear();
  for (const b of builtins) {
    builtinDeclLine.set(b.name, lines.length);
    lines.push(`\t${b.returnType} ${b.name}(${b.params.join(", ")});`);
  }
  lines.push("}");
  fs.writeFileSync(f, lines.join("\n") + "\n", "utf8");
  builtinDeclUri = URI.file(f).toString();
}

async function refreshBuiltinSignatures(): Promise<void> {
  if (builtinLoadInFlight) return;
  builtinLoadInFlight = true;
  try {
    const script = path.join(extensionRoot, "scripts", "kval_builtin_signatures.py");
    if (!extensionRoot || !fs.existsSync(script)) return;
    const child = spawn(pythonPath, [script], {
      env: { ...process.env, PYTHONPATH: pythonSysPathRoot || process.cwd() },
      windowsHide: true,
    });
    let out = "";
    let err = "";
    child.stdout?.on("data", (d: Buffer) => {
      out += d.toString("utf8");
    });
    child.stderr?.on("data", (d: Buffer) => {
      err += d.toString("utf8");
    });
    const code: number = await new Promise((resolve) => child.on("close", (c) => resolve(c ?? 1)));
    if (code !== 0 || !out.trim()) {
      if (err.trim()) connection.console.error(`builtin signature load failed: ${err.trim()}`);
      return;
    }
    const parsed = JSON.parse(out) as Array<{
      name: string;
      returnType: string;
      signature: string;
      params: Array<{ name: string; type: string; kind: string; has_default: boolean }>;
    }>;
    BUILTIN_FUNCS = parsed.map((p) => ({
      name: p.name,
      returnType: p.returnType || "object",
      signature: p.signature,
      params: p.params.map((x) =>
        x.kind === "VAR_POSITIONAL" ? `...${x.name}` : `${x.type} ${x.name}`
      ),
      doc: "自动解析于 builtin_namespace",
    }));
    generateBuiltinDeclFile(BUILTIN_FUNCS);
  } catch (e) {
    connection.console.error(`builtin signature load exception: ${String(e)}`);
  } finally {
    builtinLoadInFlight = false;
  }
}

function kvalLibRootsFromSettings(): string[] {
  const out: string[] = [];
  const pushIfDir = (p: string) => {
    if (!p) return;
    if (!fs.existsSync(p)) return;
    try {
      if (fs.statSync(p).isDirectory()) out.push(p);
    } catch {
      // ignore invalid path
    }
  };

  // Typical repo root style: <root>/Kval/Lib
  pushIfDir(path.join(pythonSysPathRoot || "", "Kval", "Lib"));
  // If user points directly to Kval root.
  pushIfDir(path.join(pythonSysPathRoot || "", "Lib"));
  // Fallback from all workspace folders.
  for (const root of workspaceRoots) {
    pushIfDir(path.join(root, "Kval", "Lib"));
    pushIfDir(path.join(root, "Lib"));
  }
  return [...new Set(out.map((p) => path.resolve(p)))];
}

function scanFilesRecursive(root: string, base: string, out: string[], depth = 0): void {
  if (!root || depth > 6) return;
  let ents: fs.Dirent[];
  try {
    ents = fs.readdirSync(root, { withFileTypes: true });
  } catch {
    return;
  }
  for (const e of ents) {
    if (e.name.startsWith(".")) continue;
    const full = path.join(root, e.name);
    if (e.isDirectory()) {
      if (e.name === "__pycache__" || e.name === ".git" || e.name === "node_modules") continue;
      scanFilesRecursive(full, base, out, depth + 1);
    } else if (e.isFile()) {
      const rel = path.relative(base, full).replace(/\\/g, "/");
      out.push(rel);
    }
  }
}

function includePathCompletions(doc: TextDocument, linePrefix: string): CompletionItem[] {
  const out: CompletionItem[] = [];
  const m = linePrefix.match(/^\s*#include\s+([<"])([^>"\n\r]*)$/);
  if (!m) return out;
  const kind = m[1];
  const typed = m[2] ?? "";
  const fileDir = path.dirname(URI.parse(doc.uri).fsPath);
  const libRoots = kvalLibRootsFromSettings();

  type SourceTag = "cwd" | "lib";
  const candidates = new Map<string, SourceTag>();
  const addFrom = (root: string, source: SourceTag) => {
    const acc: string[] = [];
    scanFilesRecursive(root, root, acc);
    for (const r of acc) {
      if (!candidates.has(r)) candidates.set(r, source);
    }
  };

  if (kind === '"') addFrom(fileDir, "cwd");
  for (const root of libRoots) addFrom(root, "lib");

  const closing = kind === "<" ? ">" : '"';
  for (const [rel, source] of candidates) {
    if (typed && !rel.toLowerCase().startsWith(typed.toLowerCase())) continue;
    out.push({
      label: rel,
      kind: CompletionItemKind.File,
      insertText: rel + closing,
      detail: source === "cwd" ? "cwd" : "Kval/Lib",
      sortText: `${source === "cwd" ? "0" : "1"}:${rel.toLowerCase()}`,
    });
  }
  return out.sort(
    (a, b) =>
      String(a.sortText ?? "").localeCompare(String(b.sortText ?? "")) ||
      String(a.label).localeCompare(String(b.label))
  );
}

interface KvalInitSettings {
  extensionRoot?: string;
  pythonPath?: string;
  workspaceRoot?: string;
  pythonSysPathRoot?: string;
  diagnosticsEnabled?: boolean;
  diagnosticsDelayMs?: number;
}

function applySettings(s: KvalInitSettings): void {
  if (s.extensionRoot !== undefined) extensionRoot = s.extensionRoot;
  if (s.pythonPath !== undefined) pythonPath = s.pythonPath;
  if (s.pythonSysPathRoot !== undefined && s.pythonSysPathRoot.trim()) {
    pythonSysPathRoot = s.pythonSysPathRoot.trim();
  } else if (s.workspaceRoot !== undefined) {
    pythonSysPathRoot = s.workspaceRoot.trim();
  }
  if (s.diagnosticsEnabled !== undefined) diagnosticsEnabled = s.diagnosticsEnabled;
  if (s.diagnosticsDelayMs !== undefined) diagnosticsDelayMs = s.diagnosticsDelayMs;
}

function workspaceFolderFs(params: InitializeParams): string {
  const wf = params.workspaceFolders?.[0]?.uri;
  if (!wf) return "";
  return URI.parse(wf).fsPath;
}

function collectRoots(params: InitializeParams): string[] {
  return (params.workspaceFolders ?? []).map((f) => URI.parse(f.uri).fsPath);
}

function openDocTexts(): Map<string, string> {
  const m = new Map<string, string>();
  for (const d of documents.all()) {
    m.set(d.uri, d.getText());
  }
  return m;
}

connection.onInitialize((params: InitializeParams) => {
  workspaceRoots = collectRoots(params);
  const wf = workspaceFolderFs(params);
  const init = (params.initializationOptions ?? {}) as KvalInitSettings;
  applySettings({
    ...init,
    pythonSysPathRoot: init.pythonSysPathRoot || init.workspaceRoot || wf,
  });
  void refreshBuiltinSignatures();
  return {
    capabilities: {
      textDocumentSync: TextDocumentSyncKind.Incremental,
      completionProvider: {
        resolveProvider: false,
        triggerCharacters: [".", ":", "<", '"', "/"],
      },
      hoverProvider: true,
      signatureHelpProvider: {
        triggerCharacters: ["(", ","],
      },
      definitionProvider: true,
      referencesProvider: true,
      documentSymbolProvider: true,
      codeLensProvider: { resolveProvider: false },
      semanticTokensProvider: {
        legend: semanticLegend,
        full: true,
        range: true,
      },
      documentFormattingProvider: true,
      documentRangeFormattingProvider: true,
      renameProvider: {
        prepareProvider: true,
      },
      workspaceSymbolProvider: true,
      codeActionProvider: {
        codeActionKinds: [
          CodeActionKind.QuickFix,
          CodeActionKind.Source,
          CodeActionKind.Refactor,
          CodeActionKind.Empty,
        ],
        resolveProvider: false,
      },
      documentHighlightProvider: true,
      foldingRangeProvider: true,
    },
  };
});

connection.onNotification("kval/settings", (s: KvalInitSettings) => {
  applySettings(s);
  void refreshBuiltinSignatures();
});

documents.onDidChangeContent((change) => {
  const uri = change.document.uri;
  const text = change.document.getText();
  // Immediately update a regex model, then refresh via lexer/token extractor asynchronously.
  docModels.set(uri, buildRegexModel(text));
  scheduleSymbolModel(change.document);
  scheduleValidate(change.document);
});

documents.onDidClose((e) => {
  docModels.delete(e.document.uri);
  const t = debouncers.get(e.document.uri);
  if (t) clearTimeout(t);
  debouncers.delete(e.document.uri);
  const st = symDebouncers.get(e.document.uri);
  if (st) clearTimeout(st);
  symDebouncers.delete(e.document.uri);
  connection.sendDiagnostics({ uri: e.document.uri, diagnostics: [] });
});

function scheduleValidate(doc: TextDocument): void {
  if (doc.uri.endsWith(".kvi")) {
    connection.sendDiagnostics({ uri: doc.uri, diagnostics: [] });
    return;
  }
  if (!diagnosticsEnabled) {
    connection.sendDiagnostics({ uri: doc.uri, diagnostics: [] });
    return;
  }
  const uri = doc.uri;
  const prev = debouncers.get(uri);
  if (prev) clearTimeout(prev);
  debouncers.set(
    uri,
    setTimeout(() => {
      void validateDocument(doc);
    }, diagnosticsDelayMs)
  );
}

async function runSymbolExtract(
  source: string,
  virtualPath: string
): Promise<{ ok: boolean; jsonText: string }> {
  const script = path.join(extensionRoot, "scripts", "kval_symbols.py");
  if (!extensionRoot || !fs.existsSync(script)) return { ok: false, jsonText: "" };
  return new Promise((resolve) => {
    const child = spawn(pythonPath, [script, "--stdin", virtualPath], {
      env: { ...process.env, PYTHONPATH: pythonSysPathRoot || process.cwd() },
      windowsHide: true,
    });
    let out = "";
    child.stdout?.on("data", (d: Buffer) => {
      out += d.toString("utf8");
    });
    child.stderr?.on("data", (d: Buffer) => {
      out += d.toString("utf8");
    });
    child.on("error", () => resolve({ ok: false, jsonText: "" }));
    child.on("close", (code) => resolve({ ok: code === 0, jsonText: out.trim() }));
    child.stdin?.write(source, "utf8");
    child.stdin?.end();
  });
}

function modelFromJson(jsonText: string): KvalModel | null {
  try {
    const parsed = JSON.parse(jsonText) as {
      classes: Array<{
        name: string;
        declKind: "class" | "struct";
        line: number;
        endLine: number;
        startChar: number;
        members: Array<{
          name: string;
          kind: "method" | "field" | "ctor";
          detail: string;
          line: number;
          startChar: number;
        }>;
      }>;
      functions: Array<{
        name: string;
        params: string;
        returnType: string;
        line: number;
        startChar: number;
      }>;
      globals: Array<{ name: string; typeName: string; line: number; startChar: number }>;
      locals?: Array<{
        name: string;
        typeName: string;
        line: number;
        startChar: number;
        scopeStartLine: number;
        scopeEndLine: number;
      }>;
      params?: Array<{
        name: string;
        typeName: string;
        line: number;
        startChar: number;
        scopeStartLine: number;
        scopeEndLine: number;
      }>;
    };
    const classes = new Map<string, any>();
    for (const c of parsed.classes ?? []) {
      classes.set(c.name, {
        name: c.name,
        declKind: c.declKind,
        line: c.line,
        endLine: c.endLine,
        startChar: c.startChar,
        members: (c.members ?? []).map((m) => ({
          name: m.name,
          kind: m.kind,
          detail: m.detail,
          line: m.line,
          startChar: m.startChar,
        })),
      });
    }
    return {
      modelSource: "lexer",
      classes: classes as unknown as Map<string, any>,
      functions: (parsed.functions ?? []).map((f) => ({
        name: f.name,
        params: f.params,
        returnType: f.returnType,
        line: f.line,
        startChar: f.startChar,
      })),
      globals: (parsed.globals ?? []).map((g) => ({
        name: g.name,
        typeName: g.typeName,
        line: g.line,
        startChar: g.startChar,
      })),
      locals: (parsed.locals ?? []).map((v) => ({
        name: v.name,
        typeName: v.typeName,
        line: v.line,
        startChar: v.startChar,
        scopeStartLine: v.scopeStartLine,
        scopeEndLine: v.scopeEndLine,
      })),
      params: (parsed.params ?? []).map((v) => ({
        name: v.name,
        typeName: v.typeName,
        line: v.line,
        startChar: v.startChar,
        scopeStartLine: v.scopeStartLine,
        scopeEndLine: v.scopeEndLine,
      })),
    };
  } catch {
    return null;
  }
}

function scheduleSymbolModel(doc: TextDocument): void {
  const uri = doc.uri;
  const prev = symDebouncers.get(uri);
  if (prev) clearTimeout(prev);
  symDebouncers.set(
    uri,
    setTimeout(
      () => {
        void (async () => {
          const { ok, jsonText } = await runSymbolExtract(doc.getText(), URI.parse(doc.uri).fsPath);
          if (!ok || !jsonText) {
            docModels.set(uri, buildRegexModel(doc.getText()));
            return;
          }
          const m = modelFromJson(jsonText);
          docModels.set(uri, m ?? buildRegexModel(doc.getText()));
          // Lexer model arrives asynchronously; force client to re-request semantic tokens.
          try {
            void connection.languages.semanticTokens.refresh();
          } catch {
            // ignore refresh errors on clients that do not support it
          }
        })();
      },
      Math.max(80, Math.min(600, diagnosticsDelayMs))
    )
  );
}

function parseParserErrorMessage(msg: string): { line: number; character: number } | undefined {
  const m = /at (\d+):(\d+)/.exec(msg);
  if (m) {
    return {
      line: Math.max(0, parseInt(m[1], 10) - 1),
      character: Math.max(0, parseInt(m[2], 10) - 1),
    };
  }
  const m2 = /at (\d+)\b/.exec(msg);
  if (m2) {
    return { line: Math.max(0, parseInt(m2[1], 10) - 1), character: 0 };
  }
  return undefined;
}

function runParserCheck(
  source: string,
  virtualPath: string
): Promise<{ ok: boolean; text: string }> {
  const script = path.join(extensionRoot, "scripts", "kval_check.py");
  return new Promise((resolve) => {
    const child = spawn(pythonPath, [script, "--stdin", virtualPath], {
      env: { ...process.env, PYTHONPATH: pythonSysPathRoot || process.cwd() },
      windowsHide: true,
    });
    let out = "";
    child.stdout?.on("data", (d: Buffer) => {
      out += d.toString("utf8");
    });
    child.stderr?.on("data", (d: Buffer) => {
      out += d.toString("utf8");
    });
    child.on("error", (e: Error) => {
      resolve({ ok: false, text: String(e.message) });
    });
    child.on("close", (code) => {
      resolve({ ok: code === 0, text: out.trim() });
    });
    child.stdin?.write(source, "utf8");
    child.stdin?.end();
  });
}

async function validateDocument(doc: TextDocument): Promise<void> {
  const script = path.join(extensionRoot, "scripts", "kval_check.py");
  if (!extensionRoot || !fs.existsSync(script)) {
    connection.sendDiagnostics({ uri: doc.uri, diagnostics: [] });
    return;
  }
  const virtualPath = URI.parse(doc.uri).fsPath;
  const { ok, text } = await runParserCheck(doc.getText(), virtualPath);
  if (ok) {
    connection.sendDiagnostics({ uri: doc.uri, diagnostics: [] });
    return;
  }
  const pos = parseParserErrorMessage(text);
  const diagnostic: Diagnostic = {
    severity: DiagnosticSeverity.Error,
    range: pos
      ? Range.create(pos.line, pos.character, pos.line, pos.character + 1)
      : Range.create(0, 0, 0, 1),
    message: text || "解析失败",
    source: "kval",
  };
  connection.sendDiagnostics({ uri: doc.uri, diagnostics: [diagnostic] });
}

function getModel(doc: TextDocument): KvalModel {
  let m = docModels.get(doc.uri);
  if (!m) {
    m = buildRegexModel(doc.getText());
    docModels.set(doc.uri, m);
    scheduleSymbolModel(doc);
  }
  return m;
}

function textBefore(doc: TextDocument, pos: { line: number; character: number }): string {
  const off = doc.offsetAt(pos);
  return doc.getText().slice(0, off);
}

function memberContext(
  doc: TextDocument,
  pos: { line: number; character: number }
): { clsName: string } | undefined {
  const before = textBefore(doc, pos);
  const model = getModel(doc);
  const arrow = before.match(/(\bthis\b|[A-Za-z_][\w]*)\s*->\s*$/);
  if (arrow) {
    const lhs = arrow[1];
    if (lhs === "this") {
      const cur = classContainingLine(model, pos.line);
      if (cur) return { clsName: cur.name };
    } else {
      const g = model.globals.find((x) => x.name === lhs);
      if (g && model.classes.has(g.typeName)) return { clsName: g.typeName };
      for (const fn of model.functions) {
        if (fn.name === lhs && model.classes.has(fn.returnType)) {
          return { clsName: fn.returnType };
        }
      }
    }
  }
  const dot = before.match(/(\bthis\b|[A-Za-z_][\w]*)\s*\.\s*$/);
  if (dot) {
    const lhs = dot[1];
    if (lhs === "this") {
      const cur = classContainingLine(model, pos.line);
      if (cur) return { clsName: cur.name };
    } else {
      const g = model.globals.find((x) => x.name === lhs);
      if (g && model.classes.has(g.typeName)) return { clsName: g.typeName };
    }
  }
  return undefined;
}

connection.onCompletion((params) => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return [];
  const pos = params.position;
  const model = getModel(doc);
  const items: CompletionItem[] = [];
  const lineText = doc.getText().split(/\r?\n/)[pos.line] ?? "";
  const linePrefix = lineText.slice(0, pos.character);
  const inc = includePathCompletions(doc, linePrefix);
  if (inc.length) return inc;
  if (/^\s*#/.test(linePrefix) || /^\s*$/.test(linePrefix)) {
    for (const p of PREPROCESSOR_ITEMS) {
      items.push({
        label: p.label,
        kind: CompletionItemKind.Keyword,
        insertText: p.insertText,
        detail: "preprocessor",
        documentation: { kind: MarkupKind.Markdown, value: p.doc },
      });
    }
    if (/^\s*#/.test(linePrefix)) return items;
  }

  const mc = memberContext(doc, pos);
  if (mc) {
    const cls = model.classes.get(mc.clsName);
    if (cls) {
      for (const mem of cls.members) {
        const kind =
          mem.kind === "field"
            ? CompletionItemKind.Field
            : mem.kind === "ctor"
              ? CompletionItemKind.Constructor
              : CompletionItemKind.Method;
        items.push({
          label: mem.name,
          kind,
          detail: mem.detail,
          documentation: { kind: MarkupKind.Markdown, value: `\`${mem.detail}\`` },
        });
      }
    }
    return items;
  }

  for (const w of KW) {
    items.push({
      label: w,
      kind: CompletionItemKind.Keyword,
    });
  }
  for (const [name, cls] of model.classes) {
    items.push({
      label: name,
      kind: cls.declKind === "struct" ? CompletionItemKind.Struct : CompletionItemKind.Class,
      detail: cls.declKind,
    });
    for (const mem of cls.members) {
      items.push({
        label: `${name}.${mem.name}`,
        kind: mem.kind === "field" ? CompletionItemKind.Field : CompletionItemKind.Method,
        insertText: mem.name,
        detail: mem.detail,
      });
    }
  }
  for (const f of model.functions) {
    items.push({
      label: f.name,
      kind: CompletionItemKind.Function,
      detail: `${f.returnType} ${f.name}(${f.params})`,
    });
  }
  for (const g of model.globals) {
    items.push({
      label: g.name,
      kind: CompletionItemKind.Variable,
      detail: `${g.typeName} ${g.name}`,
    });
  }
  for (const b of BUILTIN_FUNCS) {
    items.push({
      label: b.name,
      kind: CompletionItemKind.Function,
      detail: b.signature,
      documentation: { kind: MarkupKind.Markdown, value: b.doc },
    });
    items.push({
      label: `builtins::${b.name}`,
      kind: CompletionItemKind.Function,
      detail: b.signature,
      documentation: { kind: MarkupKind.Markdown, value: `builtins 命名空间\n\n${b.doc}` },
    });
  }
  return items;
});

connection.onHover((params): Hover | null => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return null;
  const off = doc.offsetAt(params.position);
  const text = doc.getText();
  const { word, start } = findWordAt(text, off);
  if (!word) return null;
  const model = getModel(doc);
  if (KW.includes(word)) {
    return {
      contents: { kind: MarkupKind.Markdown, value: `**关键字** \`${word}\`` },
    };
  }
  const cls = model.classes.get(word);
  if (cls) {
    return {
      contents: {
        kind: MarkupKind.Markdown,
        value: `**${cls.declKind}** \`${word}\`\n\n成员：${cls.members.map((m) => m.name).join(", ") || "（无）"}`,
      },
    };
  }
  for (const c of model.classes.values()) {
    const mem = c.members.find((m) => m.name === word);
    if (mem) {
      return {
        contents: {
          kind: MarkupKind.Markdown,
          value: `**${mem.kind}** \`${mem.detail}\`\n\n*类 ${c.name}*`,
        },
      };
    }
  }
  for (const f of model.functions) {
    if (f.name === word) {
      return {
        contents: {
          kind: MarkupKind.Markdown,
          value: `**函数** \`${f.returnType} ${f.name}(${f.params})\``,
        },
      };
    }
  }
  for (const g of model.globals) {
    if (g.name === word) {
      return {
        contents: {
          kind: MarkupKind.Markdown,
          value: `**变量** \`${g.typeName} ${g.name}\``,
        },
      };
    }
  }
  const builtin = builtinByName(word);
  if (builtin) {
    return {
      contents: {
        kind: MarkupKind.Markdown,
        value: `**内置函数** \`${builtin.signature}\`\n\n${builtin.doc}`,
      },
    };
  }
  const pp = preprocessByName(word);
  if (pp) {
    return {
      contents: {
        kind: MarkupKind.Markdown,
        value: `**预处理指令** \`${pp.label}\`\n\n${pp.doc}`,
      },
    };
  }
  const wstart = doc.positionAt(start);
  return {
    contents: { kind: MarkupKind.Markdown, value: `\`${word}\`（未知符号）` },
    range: Range.create(wstart, doc.positionAt(start + word.length)),
  };
});

connection.onSignatureHelp((params): SignatureHelp | null => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return null;
  const before = textBefore(doc, params.position);
  const m = before.match(/([A-Za-z_][\w]*)\s*\([^)]*$/);
  if (!m) return null;
  const name = m[1];
  const model = getModel(doc);
  for (const f of model.functions) {
    if (f.name === name) {
      const sig = SignatureInformation.create(
        `${f.returnType} ${f.name}(${f.params})`,
        undefined,
        ...splitParams(f.params).map((p) => ParameterInformation.create(p))
      );
      return { signatures: [sig], activeSignature: 0, activeParameter: 0 };
    }
  }
  for (const c of model.classes.values()) {
    const mem = c.members.find(
      (x) => x.name === name && (x.kind === "method" || x.kind === "ctor")
    );
    if (mem) {
      const inner = mem.detail.match(/\(([^)]*)\)/);
      const plist = inner ? inner[1] : "";
      const sig = SignatureInformation.create(
        mem.detail,
        undefined,
        ...splitParams(plist).map((p) => ParameterInformation.create(p))
      );
      return { signatures: [sig], activeSignature: 0, activeParameter: 0 };
    }
  }
  const builtin = builtinByName(name);
  if (builtin) {
    const sig = SignatureInformation.create(
      builtin.signature,
      builtin.doc,
      ...splitParams((builtin.signature.match(/\((.*)\)/)?.[1] ?? "").trim()).map((p) =>
        ParameterInformation.create(p)
      )
    );
    return { signatures: [sig], activeSignature: 0, activeParameter: 0 };
  }
  return null;
});

function splitParams(plist: string): string[] {
  if (!plist.trim()) return [];
  return plist.split(",").map((s) => s.trim());
}

function localDefinition(doc: TextDocument, word: string): Location[] | null {
  const model = getModel(doc);
  const cls = model.classes.get(word);
  if (cls) {
    return [
      Location.create(
        doc.uri,
        Range.create(cls.line, cls.startChar, cls.line, cls.startChar + word.length)
      ),
    ];
  }
  for (const c of model.classes.values()) {
    const mem = c.members.find((m) => m.name === word);
    if (mem) {
      const lineText = doc.getText().split(/\r?\n/)[mem.line] ?? "";
      const ch = Math.max(0, lineText.indexOf(word));
      return [Location.create(doc.uri, Range.create(mem.line, ch, mem.line, ch + word.length))];
    }
  }
  for (const f of model.functions) {
    if (f.name === word) {
      const lineText = doc.getText().split(/\r?\n/)[f.line] ?? "";
      const ch = Math.max(0, lineText.indexOf(word));
      return [Location.create(doc.uri, Range.create(f.line, ch, f.line, ch + word.length))];
    }
  }
  for (const g of model.globals) {
    if (g.name === word) {
      const lineText = doc.getText().split(/\r?\n/)[g.line] ?? "";
      const ch = Math.max(0, lineText.indexOf(word));
      return [Location.create(doc.uri, Range.create(g.line, ch, g.line, ch + word.length))];
    }
  }
  const b = builtinByName(word);
  if (b && builtinDeclUri && builtinDeclLine.has(b.name)) {
    const ln = builtinDeclLine.get(b.name) ?? 0;
    return [Location.create(builtinDeclUri, Range.create(ln, 0, ln, b.name.length + 32))];
  }
  return null;
}

connection.onDefinition((params): Location[] | null => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return null;
  const off = doc.offsetAt(params.position);
  const text = doc.getText();
  const { word } = findWordAt(text, off);
  if (!word) return null;
  const loc = localDefinition(doc, word);
  if (loc) return loc;
  const { defs } = buildSymbolIndex(workspaceRoots, openDocTexts());
  const hits = defs.filter((d) => d.name === word);
  if (hits.length === 0) return null;
  return hits.map((d) => Location.create(d.uri, d.range));
});

connection.onReferences((params): Location[] | null => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return null;
  const off = doc.offsetAt(params.position);
  const text = doc.getText();
  const { word } = findWordAt(text, off);
  if (!word) return null;
  const model = getModel(doc);
  const resolved = resolveSymbolAt(doc, params.position, model);
  const open = openDocTexts();
  if (resolved) {
    const rk = resolved.kind as RefKind;
    const occ = symbolOccurrenceRanges(
      rk,
      resolved.name,
      resolved.containerClass,
      workspaceRoots,
      open
    );
    const locs: Location[] = [];
    for (const [uri, ranges] of occ) {
      for (const r of ranges) {
        locs.push(Location.create(uri, r));
      }
    }
    return locs;
  }
  const re = new RegExp(`\\b${escapeRe(word)}\\b`, "g");
  const locs: Location[] = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(text))) {
    const st = doc.positionAt(m.index);
    const en = doc.positionAt(m.index + word.length);
    locs.push(Location.create(doc.uri, Range.create(st, en)));
  }
  return locs;
});

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

connection.onDocumentSymbol((params): DocumentSymbol[] => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return [];
  const model = getModel(doc);
  const out: DocumentSymbol[] = [];
  for (const c of model.classes.values()) {
    const children: DocumentSymbol[] = c.members.map((mem) => ({
      name: mem.name,
      kind:
        mem.kind === "field"
          ? SymbolKind.Field
          : mem.kind === "ctor"
            ? SymbolKind.Constructor
            : SymbolKind.Method,
      range: Range.create(mem.line, 0, mem.line, 120),
      selectionRange: Range.create(
        mem.line,
        mem.startChar,
        mem.line,
        mem.startChar + mem.name.length
      ),
      detail: mem.detail,
    }));
    out.push({
      name: c.name,
      kind: c.declKind === "struct" ? SymbolKind.Struct : SymbolKind.Class,
      range: Range.create(c.line, 0, c.endLine, 120),
      selectionRange: Range.create(c.line, c.startChar, c.line, c.startChar + c.name.length + 6),
      children,
    });
  }
  for (const f of model.functions) {
    out.push({
      name: f.name,
      kind: SymbolKind.Function,
      range: Range.create(f.line, 0, f.line, 160),
      selectionRange: Range.create(f.line, f.startChar, f.line, f.startChar + f.name.length),
      detail: `${f.returnType}(${f.params})`,
    });
  }
  for (const g of model.globals) {
    out.push({
      name: g.name,
      kind: SymbolKind.Variable,
      range: Range.create(g.line, 0, g.line, 120),
      selectionRange: Range.create(g.line, g.startChar, g.line, g.startChar + g.name.length),
      detail: g.typeName,
    });
  }
  return out;
});

connection.onCodeLens((params: CodeLensParams): CodeLens[] => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return [];
  const lines = doc.getText().split(/\r?\n/);
  const lenses: CodeLens[] = [];
  for (let i = 0; i < lines.length; i++) {
    if (/\bint\s+main\s*\(/.test(lines[i])) {
      lenses.push({
        range: Range.create(i, 0, i, 1),
        command: { title: "▶ Kval 运行", command: "kval.runFile", arguments: [] },
      });
    }
  }
  return lenses;
});

function symKindToLsp(k: SymKind): SymbolKind {
  switch (k) {
    case "class":
      return SymbolKind.Class;
    case "function":
      return SymbolKind.Function;
    case "global":
      return SymbolKind.Variable;
    case "field":
      return SymbolKind.Field;
    case "method":
      return SymbolKind.Method;
    default:
      return SymbolKind.Object;
  }
}

connection.onWorkspaceSymbol((params) => {
  const q = (params.query || "").toLowerCase().trim();
  const { defs } = buildSymbolIndex(workspaceRoots, openDocTexts());
  return defs
    .filter(
      (d) => !q || d.name.toLowerCase().includes(q) || d.containerClass?.toLowerCase().includes(q)
    )
    .map((d) => ({
      name: d.containerClass ? `${d.containerClass}.${d.name}` : d.name,
      kind: symKindToLsp(d.kind),
      location: Location.create(d.uri, d.range),
      containerName: d.containerClass,
    }));
});

function emptySemanticTokens() {
  return new SemanticTokensBuilder().build();
}

connection.languages.semanticTokens.on((params) => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return emptySemanticTokens();
  return buildSemanticTokens(doc, getModel(doc));
});

connection.languages.semanticTokens.onRange((params) => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return emptySemanticTokens();
  return buildSemanticTokens(doc, getModel(doc));
});

connection.onDocumentFormatting((params) => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return [];
  const o: FormatOptions = {
    tabSize: params.options.tabSize,
    insertSpaces: params.options.insertSpaces,
  };
  const next = formatKvalDocument(doc.getText(), o);
  const end = doc.positionAt(doc.getText().length);
  return [TextEdit.replace(Range.create(Position.create(0, 0), end), next)];
});

connection.onDocumentRangeFormatting((params) => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return [];
  const o: FormatOptions = {
    tabSize: params.options.tabSize,
    insertSpaces: params.options.insertSpaces,
  };
  const next = formatRange(doc.getText(), params.range, o);
  const end = doc.positionAt(doc.getText().length);
  return [TextEdit.replace(Range.create(Position.create(0, 0), end), next)];
});

connection.onPrepareRename((params) => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return null;
  const text = doc.getText();
  const { word, start } = findWordAt(text, doc.offsetAt(params.position));
  if (!word || KW.includes(word)) return null;
  const st = doc.positionAt(start);
  const en = doc.positionAt(start + word.length);
  return { range: Range.create(st, en), placeholder: word };
});

connection.onRenameRequest((params) => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return null;
  const newName = params.newName;
  if (!newName || !/^[A-Za-z_]\w*$/.test(newName)) {
    return null;
  }
  const model = getModel(doc);
  const resolved = resolveSymbolAt(doc, params.position, model);
  const open = openDocTexts();
  const changes: { [uri: string]: TextEdit[] } = {};
  if (resolved) {
    const rk = resolved.kind as RefKind;
    const occ = symbolOccurrenceRanges(
      rk,
      resolved.name,
      resolved.containerClass,
      workspaceRoots,
      open
    );
    for (const [uri, ranges] of occ) {
      const sorted = [...ranges].sort(
        (a, b) =>
          b.start.line - a.start.line ||
          b.start.character - a.start.character ||
          b.end.character - a.end.character
      );
      changes[uri] = sorted.map((r) => TextEdit.replace(r, newName));
    }
    return { changes };
  }
  const { word } = findWordAt(doc.getText(), doc.offsetAt(params.position));
  if (!word) return null;
  const ranges = rangesOfWordPerLine(doc.getText(), word).sort(
    (a, b) => b.start.line - a.start.line || b.start.character - a.start.character
  );
  changes[doc.uri] = ranges.map((r) => TextEdit.replace(r, newName));
  return { changes };
});

connection.onCodeAction((params) => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return [];
  const actions: CodeAction[] = [];
  actions.push({
    title: "Kval: 运行当前文件",
    kind: CodeActionKind.Empty,
    command: { command: "kval.runFile", title: "运行" },
  });
  actions.push({
    title: "Kval: 编译当前文件",
    kind: CodeActionKind.Empty,
    command: { command: "kval.compileFile", title: "编译" },
  });
  actions.push({
    title: "格式化文档",
    kind: CodeActionKind.SourceFixAll,
    command: { command: "editor.action.formatDocument", title: "格式化" },
  });
  if (params.context.diagnostics?.length) {
    actions.push({
      title: "查看 Kval 解析错误说明",
      kind: CodeActionKind.QuickFix,
      diagnostics: params.context.diagnostics,
      command: { command: "kval.showOutput", title: "输出" },
    });
  }
  return actions;
});

connection.onDocumentHighlight((params) => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return [];
  const text = doc.getText();
  const model = getModel(doc);
  const resolved = resolveSymbolAt(doc, params.position, model);
  if (resolved) {
    const occ = symbolOccurrenceRanges(
      resolved.kind as RefKind,
      resolved.name,
      resolved.containerClass,
      workspaceRoots,
      openDocTexts()
    );
    const rs = occ.get(doc.uri) ?? [];
    return rs.map((r) => ({
      range: r,
      kind: DocumentHighlightKind.Read,
    }));
  }
  const { word } = findWordAt(text, doc.offsetAt(params.position));
  if (!word) return [];
  return rangesOfWordPerLine(text, word).map((r) => ({
    range: r,
    kind: DocumentHighlightKind.Text,
  }));
});

connection.languages.foldingRange.on((params) => {
  const doc = documents.get(params.textDocument.uri);
  if (!doc) return [];
  const lines = doc.getText().split(/\r?\n/);
  const out: FoldingRange[] = [];
  const stack: number[] = [];
  for (let li = 0; li < lines.length; li++) {
    const line = lines[li];
    for (let j = 0; j < line.length; j++) {
      if (line[j] === "{") stack.push(li);
      else if (line[j] === "}") {
        const startLine = stack.pop();
        if (startLine !== undefined && startLine < li) {
          out.push({
            startLine,
            endLine: li,
            kind: FoldingRangeKind.Region,
          });
        }
      }
    }
  }
  return out;
});

documents.onDidOpen((e) => {
  docModels.set(e.document.uri, buildRegexModel(e.document.getText()));
  scheduleSymbolModel(e.document);
  scheduleValidate(e.document);
});

documents.listen(connection);
connection.listen();
